version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - /mnt/data/nas-servers/paperless:/mnt/data/nas-servers/paperless

volumes:
  portainer_data:
